version: "3.8"

services:
  bot:
    build: .
    container_name: game-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/gamebot?schema=public
      - NODE_ENV=production

  db:
    image: postgres:15-alpine
    container_name: game-bot-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gamebot
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
