version: '3.8'

services:
  bot:
    image: game-bot-bot:latest # Используем готовый образ
    container_name: game-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /var/game-bot/data:/app/data # Абсолютные пути для прода
      - /var/game-bot/logs:/app/logs
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/gamebot?schema=public
      - NODE_ENV=production
      - LOG_TO_CONSOLE=true
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  db:
    image: postgres:15-alpine
    container_name: game-bot-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gamebot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/game-bot/postgres-data # Абсолютный путь для хранения данных БД
